# Generated by Django 2.2.1 on 2019-11-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etilometor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(blank=True, max_length=300, verbose_name='Modelo')),
                ('numero_serie', models.IntegerField(verbose_name='Numero de série')),
                ('validade', models.DateField(verbose_name='Data de validade')),
                ('local', models.CharField(blank=True, max_length=300, verbose_name='Local')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
