# Generated by Django 2.2.1 on 2019-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilometros', '0002_auto_20191126_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='etilometro',
            name='certificado',
            field=models.FileField(blank=True, null=True, upload_to='cert_etil', verbose_name='Certificado de etilômetro'),
        ),
    ]
