# Generated by Django 2.2.1 on 2019-11-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilometros', '0003_etilometro_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='etilometro',
            name='marca',
            field=models.CharField(blank=True, max_length=300, verbose_name='Marca'),
        ),
    ]
