# Generated by Django 2.2.1 on 2019-11-29 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etilometros', '0004_etilometro_marca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etilometro',
            options={'ordering': ['numero_serie'], 'verbose_name': 'Etilômetro', 'verbose_name_plural': 'Etilômetros'},
        ),
    ]
