# Generated by Django 2.2.1 on 2019-05-29 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liberacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_liberacao', models.DateField(verbose_name='Data de Liberação')),
                ('documento_liberacao', models.ImageField(upload_to='doc_liberacao', verbose_name='Documento de Liberação')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Patio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=300, verbose_name='Descrição')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
        ),
        migrations.CreateModel(
            name='Remocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaqueta', models.IntegerField(verbose_name='Plaqueta')),
                ('placa', models.CharField(max_length=7, verbose_name='Placa')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('data_vistoria', models.DateField(verbose_name='Data de Vistoria')),
                ('marca', models.CharField(max_length=300, verbose_name='Marca')),
                ('modelo', models.CharField(max_length=300, verbose_name='Modelo')),
                ('especie', models.CharField(blank=True, max_length=300, verbose_name='Especie')),
                ('tipo', models.CharField(blank=True, max_length=300, verbose_name='Tipo')),
                ('combustivel', models.CharField(blank=True, max_length=300, verbose_name='Combustível')),
                ('cor', models.CharField(blank=True, max_length=300, verbose_name='Cor')),
                ('chassi', models.CharField(blank=True, max_length=300, verbose_name='Chassi')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('documento_remocao', models.ImageField(upload_to='doc_remocao', verbose_name='Documento de Remoção')),
                ('bloqueio_judicial', models.BooleanField(blank=True, verbose_name='BJ')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('liberacao', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='remocoes.Liberacao')),
                ('patio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remocoes.Patio')),
            ],
        ),
    ]
