# Generated by Django 2.2.1 on 2019-05-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remocoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patio',
            options={'ordering': ['descricao'], 'verbose_name': 'Pátio', 'verbose_name_plural': 'Pátios'},
        ),
        migrations.AlterModelOptions(
            name='remocao',
            options={'verbose_name': 'Remoção', 'verbose_name_plural': 'Remoções'},
        ),
        migrations.AlterField(
            model_name='remocao',
            name='liberacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='remocoes.Liberacao'),
        ),
    ]
