# Generated by Django 2.2.1 on 2019-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remocoes', '0003_auto_20190530_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='liberacao',
            options={'ordering': ['data_liberacao'], 'verbose_name': 'Liberação', 'verbose_name_plural': 'Liberações'},
        ),
        migrations.AlterField(
            model_name='remocao',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='bloqueio_judicial',
            field=models.BooleanField(blank=True, null=True, verbose_name='BJ'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='combustivel',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Combustível'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='cor',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='especie',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Especie'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='marca',
            field=models.CharField(blank=True, max_length=300, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='modelo',
            field=models.CharField(blank=True, max_length=300, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='placa',
            field=models.CharField(blank=True, max_length=7, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='tipo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='uf',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
    ]
