# Generated by Django 2.2.1 on 2019-06-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remocoes', '0004_auto_20190617_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remocao',
            name='documento_remocao',
            field=models.ImageField(null=True, upload_to='doc_remocao', verbose_name='Documento de Remoção'),
        ),
    ]
