# Generated by Django 2.2.1 on 2019-06-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remocoes', '0005_auto_20190617_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remocao',
            name='documento_remocao',
            field=models.ImageField(blank=True, null=True, upload_to='doc_remocao', verbose_name='Documento de Remoção'),
        ),
    ]
