# Generated by Django 2.2.1 on 2019-11-29 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remocoes', '0006_auto_20190627_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liberacao',
            name='documento_liberacao',
            field=models.FileField(upload_to='doc_liberacao', verbose_name='Documento de Liberação'),
        ),
        migrations.AlterField(
            model_name='remocao',
            name='documento_remocao',
            field=models.FileField(blank=True, null=True, upload_to='doc_remocao', verbose_name='Documento de Remoção'),
        ),
    ]
